version: '3.1'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    command: "-c log_statement=all"
  
  redis: 
    image: redis:6
    ports:
      - "6379:6379"
      